language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
install: "pip install -r requirements.d/dev.txt"
script:
  - "py.test bepasty/ --cov=bepasty --cov-report xml --pep8"
after_success:
  - "coveralls"
env:
  - PYTHONPATH=$PYTHONPATH:bepasty/
